name: Moonshot
options:
  bundleIdPrefix: com.moonshot
settings:
  IPHONEOS_DEPLOYMENT_TARGET: "16.0"
  SWIFT_VERSION: "5.9"
targets:
  Moonshot:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: MoonshotApp.swift
      - path: App
      - path: Assets.xcassets
        buildPhase: resources
      - path: "Preview Content"
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: App/Supporting/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.moonshot.Moonshot
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
  MoonshotTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Tests
    dependencies:
      - target: Moonshot
